The utils

* Install
#+BEGIN_SRC shell
pip install -e .
#+END_SRC

* Utils

** cm
cmake tool.

- ~cm i~
#+BEGIN_SRC shell
mkdir build32
# build and install in build32
#+END_SRC

** jvm
| jvm list | list all searched jdk | |
| jvm use | choice jdk version(by set the JAVA_HOME, need open new terminal to effect) | only win|

** an_util
| wifi | turn on adb-via-wifi on connected usb device(only test only one device connected).|
| push_cart | push cert to device as system certification(need root) |

** like vscode's code
| ccode | open project in clion |
| acode | in android studio     |
| pcode | in pycharm            |
| icode | open intellij |


** gitup
It's a util to quick commit to server.

It do this following thing

When you execute ~gitup~. It will prompt a commit message.

#+BEGIN_SRC shell
git add .
git commit -a -m "Your input commit message"
git push
#+END_SRC

** remote
It's a util to save your remote server setting, and setup remote server login auto login

*** Add remote
#+BEGIN_SRC shell
remote add a-remember-name-for-login-later
# Then It will prompt input name@host and password
# And It will copy .ssh/id_rsa.pub to auto login
#+END_SRC

** List remote
#+BEGIN_SRC shell
remote list
#+END_SRC

** Login remote
#+BEGIN_SRC shell
remote a-remember-name-for-login-later
#+END_SRC

** others
| ip             | get output ip                           |
| gettopactivity | get android device top activity name |
| cmake_ex       | remove the cmake cache files            |
| jt_ex          | crawl the jetbrain active code           |


* TODOS
How to let the jt_code use for private.


* Sync? need be access private repo.