* Install
#+BEGIN_SRC shell
pip install -e .
#+END_SRC

* TOC
| util           | desc                                 |
|----------------+--------------------------------------|
| img            | gen random img                       |
| git1           | git utils                            |
| cm             | cmake utils                          |
| ip             | get output ip                        |
| gettopactivity | get android device top activity name |
| cmake_ex       | remove the cmake cache files         |
| clean_space    | remove unused cache space etc        |
| ccode          | open project in clion                |
| acode          | in android studio                    |
| pcode          | in pycharm                           |
| icode          | open intellij                        |
| where1         | seach commands                       |
| junk_file      | create space holderfile              |
| sync_link      | link all file in folder1 to folder2  |

* commands

** git1
- `git1 view` view the remote url in browser

** where1
Only work on windows

#+BEGIN_SRC shell
 where1 qemu*
 # show all command in path that starts with qemu
#+END_SRC

** repo tool
manager git repositories.

`ro status` can show git repositories status

`ro add` can add current local directory into manager

*** Why naming ro
repo is google repo tool name

rp is already used by windows powershell

so naming ro

*** doc
Detail please see [[./handy_tool/repo][repo document]]

** cm
cmake tool.

- ~cm i~
#+BEGIN_SRC shell
mkdir build32
# build and install in build32
#+END_SRC

** img
generate a random img

** jvm
| jvm list | list all searched jdk | |
| jvm use | choice jdk version(by set the JAVA_HOME, need open new terminal to effect) | only win|

** an_util
| wifi | turn on adb-via-wifi on connected usb device(only test only one device connected).|
| push_cart | push cert to device as system certification(need root) |



** gitup
It's a util to quick commit to server.

It do this following thing

When you execute ~gitup~. It will prompt a commit message.

#+BEGIN_SRC shell
git add .
git commit -a -m "Your input commit message"
git push
#+END_SRC

** junk_file
Create an junk file wth 10M size.
#+BEGIN_SRC shell
# create an 10G junk_file
junk_file 10G

# create an 9M junk_file
junk_file 9M
# or
junk_file 9

# create an 10G9M junk_file
junk_file 10G9M
#+END_SRC
*** TODOS
- add option -random, fill the junk file with random value.
- do you want serpate sync project?

*** permission define
When create in driver ~C:~, there's a permission deny issue. You can run in a ~Run as amin~ powershell to
get ride of this.

* Sync? need be access private repo.


[{"applicationsNumber":"0","item":"发明专利","obtainedNumber":"0"},
{"applicationsNumber":"0","item":"实用新型专利","obtainedNumber":"0"},
{"applicationsNumber":"0","item":"外观设计专利","obtainedNumber":"0"},
{"applicationsNumber":"0","item":"软件著作权","obtainedNumber":"0"},{"applicationsNumber":"0","item":"其他","obtainedNumber":"0"},{"applicationsNumber":"0","item":"合计","obtainedNumber":"0"}]


        /**
         * 申请数
         */
        private String applicationsNumber;

        /**
         * 获得数
         */
        private String obtainedNumber;
